---
name: "Build"
on: [push]

jobs:
    build:
        name: "Build"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-go@v2
              with:
                  go-version: 1.18

            - run: |
                  go build -o zet cmd/main.go
                  chmod +x zet

            - uses: actions/upload-artifact@v3
              with:
                  name: zet
                  path: |
                      zet

            - uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  files: |
                      zet
